### ISSUE TITLE
`MonadError` instance

### ISSUE THREAD

**Issue by clementd-fretlink** [jfischoff/pg-transact#18]
I've found myself needing to interleave the possiblity of errors within DBT. For now, I use `lift . throwError` to throw errors, and use `runExceptT` just before running the transaction.

Implementing `MonadError e m => MonadError e (DBT m)` is trivial (with `GeneralizedNewtypeDeriving` for instance), but I'm not 100% sure about the semantics wrt transactions.

Do you think such an instance would make sense, or that it would give rise to dangerous things?
If it makes sense, I can open a PR to add it.

**Comment by jfischoff** [comment]
I haven't tried. I just assumed it would not be possible to get the correct behavior in `catchError`. However maybe it is possible to have it allocate a savepoint and revert to it in the case of an error using the existing MonadMask implementation.

**Comment by clementd-fretlink** [comment]
yes, this layer would be totally decorrelated from aborting the transaction, which would be surprising indeed.
