### ISSUE TITLE
Remove MonadThrow constraint from queryOne

### ISSUE THREAD

**Issue by antoine-fl** [jfischoff/pg-transact#3]
First thanks for this nice little lib :+1: 

In the latest version, `queryOne` and `queryOne_` got introduced however they require a `MonadThrow m` whereas `query` does not.

This means that if I want to use `queryOne` in a function, I must add `MonadThrow` to that functions and all functions calling it.
I don't see any good reason to have `MonadThrow` in the first place, so do you think it would be possible to remove it?

**Comment by antoine-fl** [comment]
Thanks for doing this!

**Comment by jfischoff** [comment]
np
